version: '3.4'

services:
  raspberry-controller-db:
    image: ${DOCKER_REGISTRY_NAME}/raspberry-controller-db
    container_name: raspberry-controller-db
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - raspberry-controller-db-data:/var/lib/postgresql/data
    restart: on-failure
    env_file: .env
    ports:
      - 5440:5432
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-h',
          'localhost',
          '-U',
          '$POSTGRES_USER',
          '-d',
          '$POSTGRES_DB',
        ]
      retries: 20
      interval: 3s
      start_period: 5s
    networks:
      - net

volumes:
  raspberry-controller-db-data:

networks:
  net:
