version: '3.4'

services:
  db:
    image: ${DOCKER_REGISTRY_NAME}/db
    container_name: db
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure
    env_file: .env
    ports:
      - 5440:5432
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-h',
          'localhost',
          '-U',
          '$POSTGRES_USER',
          '-d',
          '$POSTGRES_DB',
        ]
      retries: 20
      interval: 3s
      start_period: 5s
    networks:
      - net

  app:
    image: ${DOCKER_REGISTRY_NAME}/app
    container_name: app
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    env_file: .env
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:5000/api/health']
      interval: 5s
      retries: 30
      start_period: 20s
    ports:
      - 5000:5000
    networks:
      - net

volumes:
  db-data:

networks:
  net:
